name: Deploy Nginx Site

on:
  push:
    branches:
      - develop
      - main

jobs:
  deploy:
    runs-on: [self-hosted, linux, x64, azure-nginx]

    environment:
      name: ${{ github.ref_name == 'main' && 'production' || 'development' }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set target hosts
        run: |
          if [ "${GITHUB_REF_NAME}" = "develop" ]; then
            echo "HOSTS=10.10.2.6 10.10.2.7" >> $GITHUB_ENV
            echo "ENVIRONMENT=dev" >> $GITHUB_ENV
          elif [ "${GITHUB_REF_NAME}" = "main" ]; then
            echo "HOSTS=10.10.2.4 10.10.2.5" >> $GITHUB_ENV
            echo "ENVIRONMENT=prod" >> $GITHUB_ENV
          fi

      - name: Deploy to servers
        run: |
          for HOST in $HOSTS; do
            echo "Deploying to $ENVIRONMENT server: $HOST"

            ssh -i ~/.ssh/github_runner_deploy -o StrictHostKeyChecking=no \
              ahadmin@$HOST \
              "SERVER_NAME=\$(hostname); echo '<h1>${ENVIRONMENT} deployment from GitHub Actions 🚀</h1><p>Server: '\$SERVER_NAME'</p>' | sudo tee /var/www/html/index.html > /dev/null && sudo systemctl reload nginx"
          done